In [2]:
import numpy as np
import numpy.linalg as linalg

In [3]:
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [4]:
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
A.shape

(4, 2)

So, the 4 is the number of rows and the 2 is the number of the columns, remember it for the gods sake!!!!!

In [6]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
list1 = np.arange (start= 15, stop= 30, step= 6)

In [8]:
B = np.arange(start= 100, stop= 200, step= 10).reshape((5, 2))

In [9]:
B

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [10]:
C = np.array ([[11, 22, 33], [44, 55, 66], [77, 88, 99], [110, 120, 130]])

In [11]:
C

array([[ 11,  22,  33],
       [ 44,  55,  66],
       [ 77,  88,  99],
       [110, 120, 130]])

In [12]:
list2 = np.arange(20)

In [13]:
list2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
print(list2[5: 17])

[ 5  6  7  8  9 10 11 12 13 14 15 16]


To access the first element of a list you should use the index 0, but the last is the size of the list minus 1

In [15]:
print(C[: :3])

[[ 11  22  33]
 [110 120 130]]


It gives the first row, then counts to three and returns that row

In [16]:
col_idx = C.shape[1]-1
row_amount = C.shape[0]
print(C[0:row_amount,col_idx])

[ 33  66  99 130]


The columns have minus 1 because, if not, it tries to access the 4th column and it does not exist
The coma is used like in a vector, have that in mind to place the comas and the two dots
Slicing is like pattern matching, have that in mind as well

In [17]:
print(C[:row_amount,col_idx])

[ 33  66  99 130]


In [18]:
print(C[col_idx])

[77 88 99]


With this you asked for the 3rd element of C, so it returned the 3 row

In [19]:
print(C[:, col_idx])

[ 33  66  99 130]


Because I didn't say anything about the rows, so it just went through them all

In [23]:
a_list = [[3, 6, 9, 12], [15, 18, 21, 24], [27, 30, 33, 36], [39, 42, 45, 48], [51, 54, 57, 60]]

In [24]:
D = np.array(a_list)
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [25]:
print(D[1::2, ::2])

[[15 21]
 [39 45]]


In [26]:
E = np.array([[5, 6, 9], [21 ,18, 27]])
F = np.array([[15 ,33, 24], [4 ,7, 1]])

In [27]:
print(E + F)

[[20 39 33]
 [25 25 28]]


In [28]:
print(np.sqrt (E + F))

[[4.47213595 6.244998   5.74456265]
 [5.         5.         5.29150262]]


In [29]:
G = np.arange(start=10, stop=34).reshape(8, 3)

In [30]:
G

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [32]:
G.reshape(4, 6)

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

In [ ]:
for i in range(G.shape[0]):
    